--[[
 .____                  ________ ___.    _____                           __                
 |    |    __ _______   \_____  \\_ |___/ ____\_ __  ______ ____ _____ _/  |_  ___________ 
 |    |   |  |  \__  \   /   |   \| __ \   __\  |  \/  ___// ___\\__  \\   __\/  _ \_  __ \
 |    |___|  |  // __ \_/    |    \ \_\ \  | |  |  /\___ \\  \___ / __ \|  | (  <_> )  | \/
 |_______ \____/(____  /\_______  /___  /__| |____//____  >\___  >____  /__|  \____/|__|   
         \/          \/         \/    \/                \/     \/     \/                   
          \_Welcome to LuaObfuscator.com   (Alpha 0.10.9) ~  Much Love, Ferib 

]]--

local v0=loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))();local v1=v0.CreateLib("Duski|Hub","Serpent");local v2=v1:NewTab("Main🏡");local v3=v2:NewSection("Main");local function v4() game:GetService("ReplicatedStorage"):WaitForChild("Remote"):WaitForChild("Throw"):WaitForChild("Server"):WaitForChild("Request"):FireServer();end local function v5() game:GetService("ReplicatedStorage"):WaitForChild("Remote"):WaitForChild("Throw"):WaitForChild("Server"):WaitForChild("Request"):FireServer();end local function v6() local v14={1080.845282137394,0};game:GetService("ReplicatedStorage"):WaitForChild("Remote"):WaitForChild("Throw"):WaitForChild("Server"):WaitForChild("Landed"):InvokeServer(unpack(v14));end local function v7() local v15=game.Players.LocalPlayer.Character.HumanoidRootPart;v15.CFrame=workspace.World.ThrowArea.ThrowArea.CFrame + Vector3.new(0,4,0) ;end local v8=false;v3:NewToggle("Auto Yeet","When Toggled On It Automatically Yeets Your Friend!",function(v17) v8=v17;if v8 then task.spawn(function() while v8 do wait();v7();v4();wait(6);v6();task.wait(8);end end);end end);local function v9() game:GetService("ReplicatedStorage"):WaitForChild("Remote"):WaitForChild("Player"):WaitForChild("Server"):WaitForChild("AttemptRebirth"):InvokeServer();end v3:NewButton("Rebirth","When Pressed It Automatically Rebirths For You!",function() v9();end);local v10=v1:NewTab("LocalPlayer🚶‍♂️");local v11=v10:NewSection("LocalPlayer🚶‍♂️");v11:NewSlider("WalkSpeed","Changes How Fast You Walk!",500,16,function(v18) game.Players.LocalPlayer.Character.Humanoid.WalkSpeed=v18;end);v11:NewSlider("JumpPower","Changes How High You Jump!",500,50,function(v20) game.Players.LocalPlayer.Character.Humanoid.JumpPower=v20;end);local v11=v10:NewSection("Game🎮");v11:NewButton("Server Hop","When Clicked It Automatically Hops To A New Server!",function() local v22=game:GetService("TeleportService");local v23=game:GetService("HttpService");local v24=game:GetService("Players");local v25=game.PlaceId;local v26=v24.LocalPlayer;local v27=game.JobId;local v28="";local function v29() local v30="https://games.roblox.com/v1/games/"   .. v25   .. "/servers/Public?limit=100&sortOrder=Asc&cursor="   .. v28 ;local v31=game:HttpGet(v30);local v32=v23:JSONDecode(v31);v28=v32.nextPageCursor or "" ;return v32.data;end for v33=1,10 do local v34=v29();for v35,v36 in pairs(v34) do if ((v36.id~=v27) and (v36.playing<v36.maxPlayers)) then v22:TeleportToPlaceInstance(v25,v36.id,v26);return;end end task.wait(1);end end);local v12=v1:NewTab("Credits👑");local v13=v12:NewSection("Owner");v13:NewLabel("Syko");local v13=v12:NewSection("Discord");v13:NewLabel("https://discord.gg/48RuQjAZkZ");
